### ISSUE TITLE
Socket writes break out

### ISSUE THREAD

**Issue by Mickael-van-der-Beek** [yaakov123/hagana#1]
Interesting project that you started.

Could you confirm that some cases have not yet been implemented in the filesystem access control layer?
I'm able to write files using the `socket` method outside of the root or node_modules directories and thus break out:

```
const fs = require('fs');
const path = require('path');

exports.run = function run () {
  const filePath = path.resolve(__dirname, '../out.txt');
  const socket = fs.openSync(filePath, 'w+');
  fs.writeSync(socket, 'yolo');
};
```

**Comment by yaakov123** [comment]
Outlining a few ways that we can solve this.

1) Prevent fs.openSync from creating a reference to a path outside of the project root
2) Allow opening a reference, but store a map between the fileDescriptor -> actualPath and then make the decision when trying to fs.writeSync

I'm more inclined to go with option 1. Thoughts?

**Comment by yaakov123** [comment]
This should now be resolved in the latest version. I ended up going with options 1 since there's no reason a module should get a handle on a file that exists outside the project root.

**Comment by Mickael-van-der-Beek** [comment]
The fix works nicely!
